# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 5, "", "agent.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0b\x61gent.proto\x12\x0fnexora.agent.v2"J\n\x0fRegisterRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x14\n\x0c\x63\x61pabilities\x18\x03 \x03(\t"N\n\x10RegisterResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t\x12\x16\n\x0eserver_version\x18\x03 \x01(\t"\x8d\x01\n\x10HeartbeatRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x13\n\x0b\x63pu_percent\x18\x03 \x01(\x02\x12\x16\n\x0ememory_percent\x18\x04 \x01(\x02\x12\x14\n\x0c\x64isk_percent\x18\x05 \x01(\x02\x12\x14\n\x0ctimestamp_ms\x18\x06 \x01(\x03"6\n\x11HeartbeatResponse\x12\x10\n\x08received\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t"T\n\x0e\x45xecuteRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x0f\n\x07package\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\t"X\n\x0f\x45xecuteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x14\n\x0c\x65xecution_id\x18\x04 \x01(\t"$\n\x10GetStatusRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t"^\n\x11GetStatusResponse\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x16\n\x0euptime_seconds\x18\x04 \x01(\x03\x32\xd5\x02\n\x0c\x41gentService\x12O\n\x08Register\x12 .nexora.agent.v2.RegisterRequest\x1a!.nexora.agent.v2.RegisterResponse\x12R\n\tHeartbeat\x12!.nexora.agent.v2.HeartbeatRequest\x1a".nexora.agent.v2.HeartbeatResponse\x12L\n\x07\x45xecute\x12\x1f.nexora.agent.v2.ExecuteRequest\x1a .nexora.agent.v2.ExecuteResponse\x12R\n\tGetStatus\x12!.nexora.agent.v2.GetStatusRequest\x1a".nexora.agent.v2.GetStatusResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "agent_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_REGISTERREQUEST"]._serialized_start = 32
    _globals["_REGISTERREQUEST"]._serialized_end = 106
    _globals["_REGISTERRESPONSE"]._serialized_start = 108
    _globals["_REGISTERRESPONSE"]._serialized_end = 186
    _globals["_HEARTBEATREQUEST"]._serialized_start = 189
    _globals["_HEARTBEATREQUEST"]._serialized_end = 330
    _globals["_HEARTBEATRESPONSE"]._serialized_start = 332
    _globals["_HEARTBEATRESPONSE"]._serialized_end = 386
    _globals["_EXECUTEREQUEST"]._serialized_start = 388
    _globals["_EXECUTEREQUEST"]._serialized_end = 472
    _globals["_EXECUTERESPONSE"]._serialized_start = 474
    _globals["_EXECUTERESPONSE"]._serialized_end = 562
    _globals["_GETSTATUSREQUEST"]._serialized_start = 564
    _globals["_GETSTATUSREQUEST"]._serialized_end = 600
    _globals["_GETSTATUSRESPONSE"]._serialized_start = 602
    _globals["_GETSTATUSRESPONSE"]._serialized_end = 696
    _globals["_AGENTSERVICE"]._serialized_start = 699
    _globals["_AGENTSERVICE"]._serialized_end = 1040
# @@protoc_insertion_point(module_scope)
